name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: asia-southeast2 # Jakarta
  REPO_NAME: nyam-repo # Pastikan repo ini ada di Artifact Registry GCP
  SERVICE_NAME: nyam-backend

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Login GCP
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      # 2. Setup SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # 3. Config Docker
      - name: Docker Auth
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      # 4. Bikin File Kunci Firebase (Magic Step)
      - name: Create Firebase Key
        run: |
          echo '${{ secrets.FIREBASE_KEY }}' > serviceAccountKey.json

      # 5. Build & Push Image (Langsung titik . karena di root)
      - name: Build and Push
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      # 6. Deploy
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          flags: "--allow-unauthenticated"
          env_vars: |
            NODE_ENV=production
            ML_API_URL=${{ secrets.ML_API_URL }}
            EDAMAM_APP_ID=${{ secrets.EDAMAM_APP_ID }}
            EDAMAM_APP_KEY=${{ secrets.EDAMAM_APP_KEY }}
            EDAMAM_USER_ID=${{ secrets.EDAMAM_USER_ID }}
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
